// Generated by Frozen Sand Particle Studio
// Thu Sep 24 17:19:26 2009
// Use on a 400x400 unit brush face

textures/null_c_fall/fall1
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall1_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 260 sin -1 1 0 0.35
	deformvertexes move 85.3317 -389.407 0 sawtooth 0 1 0 0.35
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.2 0.75 0.35
		tcMod stretch sawtooth 0.75 0.5 0.75 0.35
	}
}

textures/null_c_fall/zzfall1_1
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall1_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 280 sin -1 1 0.0769231 0.35
	deformvertexes move 125.624 -376.848 0 sawtooth 0 1 0.0769231 0.35
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.2 0.826923 0.35
		tcMod stretch sawtooth 0.75 0.5 0.826923 0.35
	}
}

textures/null_c_fall/zzfall1_2
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall1_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 283 sin -1 1 0.153846 0.35
	deformvertexes move 99.3076 -447.948 0 sawtooth 0 1 0.153846 0.35
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.2 0.903846 0.35
		tcMod stretch sawtooth 0.75 0.5 0.903846 0.35
	}
}

textures/null_c_fall/zzfall1_3
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall1_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 276 sin -1 1 0.230769 0.35
	deformvertexes move 126.657 -422.543 0 sawtooth 0 1 0.230769 0.35
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.2 0.980769 0.35
		tcMod stretch sawtooth 0.75 0.5 0.980769 0.35
	}
}

textures/null_c_fall/zzfall1_4
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall1_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 258 sin -1 1 0.307692 0.35
	deformvertexes move 121.962 -382.62 0 sawtooth 0 1 0.307692 0.35
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.2 1.05769 0.35
		tcMod stretch sawtooth 0.75 0.5 1.05769 0.35
	}
}

textures/null_c_fall/zzfall1_5
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall1_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 280 sin -1 1 0.384615 0.35
	deformvertexes move 150.694 -395.499 0 sawtooth 0 1 0.384615 0.35
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.2 1.13462 0.35
		tcMod stretch sawtooth 0.75 0.5 1.13462 0.35
	}
}

textures/null_c_fall/zzfall1_6
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall1_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 287 sin -1 1 0.461538 0.35
	deformvertexes move 170.125 -404.632 0 sawtooth 0 1 0.461538 0.35
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.2 1.21154 0.35
		tcMod stretch sawtooth 0.75 0.5 1.21154 0.35
	}
}

textures/null_c_fall/zzfall1_7
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall1_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 287 sin -1 1 0.538462 0.35
	deformvertexes move 141.005 -434.641 0 sawtooth 0 1 0.538462 0.35
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.2 1.28846 0.35
		tcMod stretch sawtooth 0.75 0.5 1.28846 0.35
	}
}

textures/null_c_fall/zzfall1_8
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall1_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 282 sin -1 1 0.615385 0.35
	deformvertexes move 75.3272 -395.179 0 sawtooth 0 1 0.615385 0.35
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.2 1.36538 0.35
		tcMod stretch sawtooth 0.75 0.5 1.36538 0.35
	}
}

textures/null_c_fall/zzfall1_9
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall1_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 259 sin -1 1 0.692308 0.35
	deformvertexes move 129.761 -395.368 0 sawtooth 0 1 0.692308 0.35
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.2 1.44231 0.35
		tcMod stretch sawtooth 0.75 0.5 1.44231 0.35
	}
}

textures/null_c_fall/zzfall1_10
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall1_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 259 sin -1 1 0.769231 0.35
	deformvertexes move 129.956 -376.31 0 sawtooth 0 1 0.769231 0.35
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.2 1.51923 0.35
		tcMod stretch sawtooth 0.75 0.5 1.51923 0.35
	}
}

textures/null_c_fall/zzfall1_11
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall1_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 284 sin -1 1 0.846154 0.35
	deformvertexes move 173.517 -438.253 0 sawtooth 0 1 0.846154 0.35
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.2 1.59615 0.35
		tcMod stretch sawtooth 0.75 0.5 1.59615 0.35
	}
}

textures/null_c_fall/zzfall1_12
{
	qer_editorimage textures/null_c/water_fall1.tga
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 282 sin -1 1 0.923077 0.35
	deformvertexes move 108.508 -400.868 0 sawtooth 0 1 0.923077 0.35
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.2 1.67308 0.35
		tcMod stretch sawtooth 0.75 0.5 1.67308 0.35
	}
}

// Generated by Frozen Sand Particle Studio
// Thu Sep 24 17:36:16 2009
// 448 Units

textures/null_c_fall/fall2
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall2_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 274 sin -1 1 0 0.27
	deformvertexes move -219.046 -472.326 0 sawtooth -0.0326517 1 0 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 0.75 0.27
		tcMod stretch sawtooth 0.75 0.5 0.75 0.27
	}
}

textures/null_c_fall/zzfall2_1
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall2_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 269 sin -1 1 0.0666667 0.27
	deformvertexes move -176.497 -435.094 0 sawtooth 0.0298171 1 0.0666667 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 0.816667 0.27
		tcMod stretch sawtooth 0.75 0.5 0.816667 0.27
	}
}

textures/null_c_fall/zzfall2_2
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall2_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 278 sin -1 1 0.133333 0.27
	deformvertexes move 12.2453 -515.796 0 sawtooth 0.0193821 1 0.133333 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 0.883333 0.27
		tcMod stretch sawtooth 0.75 0.5 0.883333 0.27
	}
}

textures/null_c_fall/zzfall2_3
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall2_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 268 sin -1 1 0.2 0.27
	deformvertexes move -52.217 -507.024 0 sawtooth 0.0372764 1 0.2 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 0.95 0.27
		tcMod stretch sawtooth 0.75 0.5 0.95 0.27
	}
}

textures/null_c_fall/zzfall2_4
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall2_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 270 sin -0.92963 1 0.266667 0.27
	deformvertexes move -20.8237 -444.866 0 sawtooth -0.0404174 1 0.266667 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.01667 0.27
		tcMod stretch sawtooth 0.75 0.5 1.01667 0.27
	}
}

textures/null_c_fall/zzfall2_5
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall2_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 267 sin -1.09738 1 0.333333 0.27
	deformvertexes move -43.609 -482.917 0 sawtooth 0.0350601 1 0.333333 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.08333 0.27
		tcMod stretch sawtooth 0.75 0.5 1.08333 0.27
	}
}

textures/null_c_fall/zzfall2_6
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall2_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 256 sin -1.02734 1 0.4 0.27
	deformvertexes move -126.84 -418.003 0 sawtooth 0.0228925 1 0.4 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.15 0.27
		tcMod stretch sawtooth 0.75 0.5 1.15 0.27
	}
}

textures/null_c_fall/zzfall2_7
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall2_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 271 sin -1.09225 1 0.466667 0.27
	deformvertexes move -116.872 -446.122 0 sawtooth 0.0325255 1 0.466667 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.21667 0.27
		tcMod stretch sawtooth 0.75 0.5 1.21667 0.27
	}
}

textures/null_c_fall/zzfall2_8
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall2_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 276 sin -1.01087 1 0.533333 0.27
	deformvertexes move 43.1413 -463.29 0 sawtooth 0.0107459 1 0.533333 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.28333 0.27
		tcMod stretch sawtooth 0.75 0.5 1.28333 0.27
	}
}

textures/null_c_fall/zzfall2_9
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall2_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 272 sin -0.915441 1 0.6 0.27
	deformvertexes move -179.696 -408.198 0 sawtooth 0.0246637 1 0.6 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.35 0.27
		tcMod stretch sawtooth 0.75 0.5 1.35 0.27
	}
}

textures/null_c_fall/zzfall2_10
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall2_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 263 sin -0.988593 1 0.666667 0.27
	deformvertexes move -40.5028 -431.692 0 sawtooth 0.041514 1 0.666667 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.41667 0.27
		tcMod stretch sawtooth 0.75 0.5 1.41667 0.27
	}
}

textures/null_c_fall/zzfall2_11
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall2_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 258 sin -0.903101 1 0.733333 0.27
	deformvertexes move -134.039 -485.3 0 sawtooth -0.0158897 1 0.733333 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.48333 0.27
		tcMod stretch sawtooth 0.75 0.5 1.48333 0.27
	}
}

textures/null_c_fall/zzfall2_12
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall2_13
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 268 sin -0.914179 1 0.8 0.27
	deformvertexes move -95.9775 -525.005 0 sawtooth 0.0168632 1 0.8 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.55 0.27
		tcMod stretch sawtooth 0.75 0.5 1.55 0.27
	}
}

textures/null_c_fall/zzfall2_13
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall2_14
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 263 sin -1 1 0.866667 0.27
	deformvertexes move 6.23759 -525.551 0 sawtooth 0.015221 1 0.866667 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.61667 0.27
		tcMod stretch sawtooth 0.75 0.5 1.61667 0.27
	}
}

textures/null_c_fall/zzfall2_14
{
	qer_editorimage textures/null_c/water_fall1.tga
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 275 sin -0.934545 1 0.933333 0.27
	deformvertexes move 76.4807 -498.639 0 sawtooth 0.00198228 1 0.933333 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.68333 0.27
		tcMod stretch sawtooth 0.75 0.5 1.68333 0.27
	}
}

// Generated by Frozen Sand Particle Studio
// Thu Sep 24 17:39:55 2009


textures/null_c_fall/fall3
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall3_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 271 sin -1 1 0 0.27
	deformvertexes move -284.891 -237.076 0 sawtooth -0.0269809 1 0 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.17 0.75 0.27
		tcMod stretch sawtooth 0.75 0.5 0.75 0.27
	}
}

textures/null_c_fall/zzfall3_1
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall3_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 269 sin -1 1 0.0666667 0.27
	deformvertexes move -285.953 -192.834 0 sawtooth -0.0289942 1 0.0666667 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.17 0.816667 0.27
		tcMod stretch sawtooth 0.75 0.5 0.816667 0.27
	}
}

textures/null_c_fall/zzfall3_2
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall3_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 284 sin -1 1 0.133333 0.27
	deformvertexes move -171.928 -301.887 0 sawtooth -0.0460549 1 0.133333 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.17 0.883333 0.27
		tcMod stretch sawtooth 0.75 0.5 0.883333 0.27
	}
}

textures/null_c_fall/zzfall3_3
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall3_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 269 sin -1 1 0.2 0.27
	deformvertexes move -346.305 -237.458 0 sawtooth -0.00952614 1 0.2 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.17 0.95 0.27
		tcMod stretch sawtooth 0.75 0.5 0.95 0.27
	}
}

textures/null_c_fall/zzfall3_4
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall3_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 276 sin -1 1 0.266667 0.27
	deformvertexes move -263.335 -273.226 0 sawtooth -0.0184468 1 0.266667 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.17 1.01667 0.27
		tcMod stretch sawtooth 0.75 0.5 1.01667 0.27
	}
}

textures/null_c_fall/zzfall3_5
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall3_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 268 sin -1 1 0.333333 0.27
	deformvertexes move -362.136 -207.817 0 sawtooth -0.0335306 1 0.333333 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.17 1.08333 0.27
		tcMod stretch sawtooth 0.75 0.5 1.08333 0.27
	}
}

textures/null_c_fall/zzfall3_6
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall3_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 267 sin -1 1 0.4 0.27
	deformvertexes move -261.668 -186.212 0 sawtooth 0.031137 1 0.4 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.17 1.15 0.27
		tcMod stretch sawtooth 0.75 0.5 1.15 0.27
	}
}

textures/null_c_fall/zzfall3_7
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall3_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 282 sin -1 1 0.466667 0.27
	deformvertexes move -337.393 -241.087 0 sawtooth -0.0192921 1 0.466667 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.17 1.21667 0.27
		tcMod stretch sawtooth 0.75 0.5 1.21667 0.27
	}
}

textures/null_c_fall/zzfall3_8
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall3_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 275 sin -1 1 0.533333 0.27
	deformvertexes move -209.057 -246.355 0 sawtooth -0.0185699 1 0.533333 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.17 1.28333 0.27
		tcMod stretch sawtooth 0.75 0.5 1.28333 0.27
	}
}

textures/null_c_fall/zzfall3_9
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall3_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 270 sin -1 1 0.6 0.27
	deformvertexes move -214.33 -253.895 0 sawtooth 0.00902895 1 0.6 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.17 1.35 0.27
		tcMod stretch sawtooth 0.75 0.5 1.35 0.27
	}
}

textures/null_c_fall/zzfall3_10
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall3_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 277 sin -1 1 0.666667 0.27
	deformvertexes move -305.338 -230.942 0 sawtooth 0.00522414 1 0.666667 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.17 1.41667 0.27
		tcMod stretch sawtooth 0.75 0.5 1.41667 0.27
	}
}

textures/null_c_fall/zzfall3_11
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall3_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 265 sin -1 1 0.733333 0.27
	deformvertexes move -138.635 -283.327 0 sawtooth -0.00634062 1 0.733333 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.17 1.48333 0.27
		tcMod stretch sawtooth 0.75 0.5 1.48333 0.27
	}
}

textures/null_c_fall/zzfall3_12
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall3_13
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 256 sin -1 1 0.8 0.27
	deformvertexes move -271.676 -159.659 0 sawtooth 0.0285608 1 0.8 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.17 1.55 0.27
		tcMod stretch sawtooth 0.75 0.5 1.55 0.27
	}
}

textures/null_c_fall/zzfall3_13
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall3_14
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 269 sin -1 1 0.866667 0.27
	deformvertexes move -152.873 -293.467 0 sawtooth 0 1 0.866667 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.17 1.61667 0.27
		tcMod stretch sawtooth 0.75 0.5 1.61667 0.27
	}
}

textures/null_c_fall/zzfall3_14
{
	qer_editorimage textures/null_c/water_fall1.tga
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 261 sin -1 1 0.933333 0.27
	deformvertexes move -257.281 -193.551 0 sawtooth 0.0465902 1 0.933333 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.17 1.68333 0.27
		tcMod stretch sawtooth 0.75 0.5 1.68333 0.27
	}
}

// Generated by Frozen Sand Particle Studio
// Thu Sep 24 17:40:36 2009


textures/null_c_fall/fall4
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall4_1
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 254 sin -1 1 0 0.27
	deformvertexes move -212.931 -152.556 0 sawtooth 0.0152706 1 0 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 0.75 0.27
		tcMod stretch sawtooth 0.75 0.5 0.75 0.27
	}
}

textures/null_c_fall/zzfall4_1
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall4_2
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 240 sin -1 1 0.08532 0.27
	deformvertexes move -129.043 -165.823 0 sawtooth -0.104703 1 0.08532 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 0.83532 0.27
		tcMod stretch sawtooth 0.75 0.5 0.83532 0.27
	}
}

textures/null_c_fall/zzfall4_2
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall4_3
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 276 sin -1 1 0.160198 0.27
	deformvertexes move -229.721 -163.967 0 sawtooth -0.0566903 1 0.160198 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 0.910198 0.27
		tcMod stretch sawtooth 0.75 0.5 0.910198 0.27
	}
}

textures/null_c_fall/zzfall4_3
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall4_4
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 274 sin -1 1 0.231583 0.27
	deformvertexes move -180.296 -160.097 0 sawtooth 0.0165894 1 0.231583 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 0.981583 0.27
		tcMod stretch sawtooth 0.75 0.5 0.981583 0.27
	}
}

textures/null_c_fall/zzfall4_4
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall4_5
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 284 sin -1 1 0.30079 0.27
	deformvertexes move -271.057 -176.956 0 sawtooth -0.027803 1 0.30079 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.05079 0.27
		tcMod stretch sawtooth 0.75 0.5 1.05079 0.27
	}
}

textures/null_c_fall/zzfall4_5
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall4_6
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 274 sin -1 1 0.368421 0.27
	deformvertexes move -184.038 -203.151 0 sawtooth -0.0620172 1 0.368421 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.11842 0.27
		tcMod stretch sawtooth 0.75 0.5 1.11842 0.27
	}
}

textures/null_c_fall/zzfall4_6
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall4_7
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 253 sin -1 1 0.434823 0.27
	deformvertexes move -265.67 -115.98 0 sawtooth 0.0137987 1 0.434823 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.18482 0.27
		tcMod stretch sawtooth 0.75 0.5 1.18482 0.27
	}
}

textures/null_c_fall/zzfall4_7
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall4_8
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 291 sin -1 1 0.500219 0.27
	deformvertexes move -214.447 -288.059 0 sawtooth 0.0361998 1 0.500219 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.25022 0.27
		tcMod stretch sawtooth 0.75 0.5 1.25022 0.27
	}
}

textures/null_c_fall/zzfall4_8
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall4_9
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 284 sin -1 1 0.564767 0.27
	deformvertexes move -209.399 -150.214 0 sawtooth 0.0698471 1 0.564767 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.31477 0.27
		tcMod stretch sawtooth 0.75 0.5 1.31477 0.27
	}
}

textures/null_c_fall/zzfall4_9
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall4_10
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 249 sin -1 1 0.628582 0.27
	deformvertexes move -209.817 -123.858 0 sawtooth -0.0287301 1 0.628582 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.37858 0.27
		tcMod stretch sawtooth 0.75 0.5 1.37858 0.27
	}
}

textures/null_c_fall/zzfall4_10
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall4_11
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 289 sin -1 1 0.691752 0.27
	deformvertexes move -205.112 -232.441 0 sawtooth -0.0322581 1 0.691752 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.44175 0.27
		tcMod stretch sawtooth 0.75 0.5 1.44175 0.27
	}
}

textures/null_c_fall/zzfall4_11
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall4_12
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 258 sin -1 1 0.754349 0.27
	deformvertexes move -260.541 -103.04 0 sawtooth 0.0535377 1 0.754349 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.50435 0.27
		tcMod stretch sawtooth 0.75 0.5 1.50435 0.27
	}
}

textures/null_c_fall/zzfall4_12
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall4_13
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 238 sin -1 1 0.816429 0.27
	deformvertexes move -153.17 -159.311 0 sawtooth -0.0678733 1 0.816429 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.56643 0.27
		tcMod stretch sawtooth 0.75 0.5 1.56643 0.27
	}
}

textures/null_c_fall/zzfall4_13
{
	qer_editorimage textures/null_c/water_fall1.tga
	q3map_cloneshader textures/null_c_fall/zzfall4_14
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 302 sin -1 1 0.878039 0.27
	deformvertexes move -325.133 -139.42 0 sawtooth -0.0424011 1 0.878039 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.62804 0.27
		tcMod stretch sawtooth 0.75 0.5 1.62804 0.27
	}
}

textures/null_c_fall/zzfall4_14
{
	qer_editorimage textures/null_c/water_fall1.tga
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nomarks
	surfaceparm nodlight
	deformvertexes move 0 0 274 sin -1 1 0.939218 0.27
	deformvertexes move -194.741 -261.589 0 sawtooth 0.0214646 1 0.939218 0.27
	deformvertexes autosprite
	cull disable
	sort 5
	{
		clampmap textures/null_c/water_fall1.tga
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		rgbgen const ( 1 1 1 )
		alphagen wave triangle 0 1.1664 1.68922 0.27
		tcMod stretch sawtooth 0.75 0.5 1.68922 0.27
	}
}

